swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api_v1

paths:
  /users:
    get:
      operationId: resource.read_all
      tags:
        - users
      summary: Read the entire list of users
      description: Read the list of users
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of users to get from users
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering users
          required: false
      responses:
        200:
          description: Successfully read users list operation
          schema:
            type: array
            items:
              properties:
                person_id:
                  type: string
                  description: Id of the person
                fname:
                  type: string
                  description: First name of the person
                lname:
                  type: string
                  description: Last name of the person
                timestamp:
                  type: string
                  description: Creation/Update timestamp of the person
                age:
                  type: integer
                  description: Age of the person
                job:
                  type: string
                  description: Job of the person

    post:
      operationId: resource.create
      tags:
        - users
      summary: Create a person
      description: Create a new person
      parameters:
        - name: person
          in: body
          description: Person to create
          required: True
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of person to create
              lname:
                type: string
                description: Last name of person to create
              age:
                type: integer
                description: Age of person to create
              job:
                type: string
                description: Job of person to create
      responses:
        201:
          description: Successfully created person in list
          schema:
            properties:
              person_id:
                type: string
                description: Id of the person
              fname:
                type: string
                description: First name of person
              lname:
                type: string
                description: Last name of person
              timestamp:
                type: string
                description: Creation/Update timestamp of the person record
              age:
                type: integer
                description: Age of person
              job:
                type: string
                description: Job of person


  /users/{person_id}:
    get:
      operationId: resource.read_one
      tags:
        - users
      summary: Read one person from the users list
      description: Read one person from the users list
      parameters:
        - name: person_id
          in: path
          description: Id the person to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read person from users list operation
          schema:
            type: object
            properties:
              person_id:
                type: string
                description: Id of the person
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
              timestamp:
                type: string
                description: Creation/Update timestamp of the person
              age:
                type: integer
                description: Age of the person
              job:
                type: string
                description: Job of person

    put:
      operationId: resource.update
      tags:
        - users
      summary: Update a person in the users list
      description: Update a person in the users list
      parameters:
        - name: person_id
          in: path
          description: Id the person to update
          type: integer
          required: True
        - name: person
          in: body
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
              age:
                type: integer
                description: Age of the person
              job:
                type: string
                description: Job of the person
      responses:
        200:
          description: Successfully updated person in users list
          schema:
            properties:
              person_id:
                type: string
                description: Id of the person
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
              timestamp:
                type: string
                description: Creation/Update timestamp of the person
              age:
                type: integer
                description: Age of the person
              job:
                type: string
                description: Job of person

    delete:
      operationId: resource.delete
      tags:
        - users
      summary: Delete a person from the users list
      description: Delete a person
      parameters:
        - name: person_id
          in: path
          type: integer
          description: Id of the person to delete
          required: True
      responses:
        200:
          description: Successfully deleted a person from users list